apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: esyfo-info-frontend
  namespace: team-esyfo
  labels:
    team: team-esyfo
spec:
  image: {{image}}
  port: 8080
  ingresses:
    - "https://esyfo-info-frontend.labs.nais.io/"
  liveness:
    path: syk/info/api/isAlive
  readiness:
    path: syk/info/api/isReady
  env:
    - name: MOCK_BACKEND
      value: "true"
    - name: ENVIRONMENT
      value: "labs"
    - name: OPPLAERING
      value: "true"
    - name: DITTNAV_URL
      value: "https://www.nav.no/person/dittnav"
    - name: DITT_SYKEFRAVAER_URL
      value: "https://ditt-sykefravaer.labs.nais.io/syk/sykefravaer"
    - name: ARBEIDSSOKERREGISTRERING_URL
      value: "https://arbeidssokerregistrering.nav.no/start?fraSykefravaer=true"
    - name: ESYFOVARSEL_HOST
      value: "https://esyfovarsel.dev.intern.nav.no"
    - name: DECORATOR_ENV
      value: "prod"
    - name: AMPLITUDE_ENABLED
      value: "false"
