apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: esyfo-info-frontend
  namespace: team-esyfo
  labels:
    team: team-esyfo
spec:
  image: {{image}}
  port: 8080
  ingresses:
    - "https://www.ekstern.dev.nav.no/syk/info"
  tokenx:
    enabled: true
  idporten:
    enabled: true
    sidecar:
      enabled: true
      level: Level4
      autoLogin: true
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: 200m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 64Mi
  liveness:
    path: syk/info/api/isAlive
  readiness:
    path: syk/info/api/isReady
  env:
    - name: MOCK_BACKEND
      value: "false"
    - name: ENVIRONMENT
      value: "q1"
    - name: OPPLAERING
      value: "false"
    - name: DITTNAV_URL
      value: "https://www.dev.nav.no/person/dittnav/"
    - name: DITT_SYKEFRAVAER_URL
      value: "https://www-gcp.dev.nav.no/syk/sykefravaer"
    - name: NARMESTELEDER_URL
      value: "https://narmesteleder.dev.nav.no"
    - name: ARBEIDSSOKERREGISTRERING_URL
      value: "https://arbeid.dev.nav.no/arbeid/registrering"
    - name: ESYFOVARSEL_HOST
      value: "http://esyfovarsel"
    - name: ESYFOVARSEL_CLIENT_ID
      value: "dev-gcp:team-esyfo:esyfovarsel"
    - name: VEILARBOPPFOLGING_CLIENT_ID
      value: "dev-fss:pto:veilarboppfolging"
    - name: DECORATOR_ENV
      value: "dev"
    - name: AMPLITUDE_ENABLED
      value: "true"
    - name: VEILARBOPPFOLGING_HOST
      value: "veilarboppfolging.dev-fss-pub.nais.io"
  accessPolicy:
    outbound:
      rules:
        - application: esyfovarsel
        - application: veilarboppfolging
          namespace: pto
      external:
        - host: dekoratoren.dev.nav.no
        - host: dekoratoren.ekstern.dev.nav.no
        - host: veilarboppfolging.dev-fss-pub.nais.io
