apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: esyfo-info-frontend-demo
  namespace: team-esyfo
  labels:
    team: team-esyfo
spec:
  image: {{image}}
  port: 8080
  ingresses:
    - "https://demo.ekstern.dev.nav.no/syk/info/"
  tokenx:
    enabled: false
  idporten:
    enabled: false
    sidecar:
      enabled: false
  liveness:
    path: syk/info/api/isAlive
  readiness:
    path: syk/info/api/isReady
  env:
    - name: MOCK_BACKEND
      value: "true"
    - name: ENVIRONMENT
      value: "demo"
    - name: OPPLAERING
      value: "true"
    - name: DITTNAV_URL
      value: "https://www.nav.no/person/dittnav"
    - name: DITT_SYKEFRAVAER_URL
      value: "https://ditt-sykefravaer.labs.nais.io/syk/sykefravaer"
    - name: ARBEIDSSOKERREGISTRERING_URL
      value: "https://arbeid.dev.nav.no/arbeid/registrering"
    - name: ESYFOVARSEL_HOST
      value: "https://esyfovarsel.dev.intern.nav.no"
    - name: DECORATOR_ENV
      value: "prod"
    - name: AMPLITUDE_ENABLED
      value: "false"
  accessPolicy:
    outbound:
      external:
        - host: www.nav.no
        - host: dekoratoren.ekstern.dev.nav.no
