apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: esyfo-info-frontend
  namespace: team-esyfo
  labels:
    team: team-esyfo
spec:
  image: {{image}}
  port: 8080
  ingresses:
    - "https://www.nav.no/syk/info"
  idporten:
    enabled: true
    sidecar:
      enabled: true
      level: Level4
      autoLogin: true
  replicas:
    min: 2
    max: 3
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: 400m
      memory: 400Mi
    requests:
      cpu: 200m
      memory: 100Mi
  liveness:
    path: syk/info/api/isAlive
  readiness:
    path: syk/info/api/isReady
  env:
    - name: MOCK_BACKEND
      value: "false"
    - name: ENVIRONMENT
      value: "prod"
    - name: OPPLAERING
      value: "false"
    - name: SYKMELDINGER_BACKEND_PROXY_ROOT
      value: "https://sykmelding-gateway.nav.no/sykmeldinger-backend"
    - name: FLEX_GATEWAY_ROOT
      value: "https://flex-gateway.nav.no"
    - name: LOGINSERVICE_URL
      value: "https://loginservice.nav.no/login"
    - name: LOGINSERVICE_REDIRECT_URL
      value: "https://www.nav.no/syk/info/snart-slutt-pa-sykepengene"
    - name: DITTNAV_URL
      value: "https://www.nav.no/person/dittnav"
    - name: DITT_SYKEFRAVAER_URL
      value: "https://www.nav.no/syk/sykefravaer"
    - name: NARMESTELEDER_URL
      value: "https://narmesteleder.nav.no"
    - name: ARBEIDSSOKERREGISTRERING_URL
      value: "https://arbeidssokerregistrering.nav.no/start?fraSykefravaer=true"
    - name: DECORATOR_ENV
      value: "prod"
    - name: AMPLITUDE_ENABLED
      value: "true"
    - name: VEILARBOPPFOLGING_HOST
      value: "veilarboppfolging.prod-fss-pub.nais.io"
