apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: esyfo-info-frontend-demo
  namespace: team-esyfo
  labels:
    team: team-esyfo
spec:
  image: {{image}}
  port: 8080
  ingresses:
    - "https://demo.ekstern.dev.nav.no/syk/info/"
  tokenx:
    enabled: false
  idporten:
    enabled: false
    sidecar:
      enabled: false
  liveness:
    path: syk/info/api/isAlive
  readiness:
    path: syk/info/api/isReady
  env:
    - name: MOCK_BACKEND
      value: "true"
    - name: ENVIRONMENT
      value: "demo"
    - name: OPPLAERING
      value: "true"
    - name: MIN_SIDE_URL
      value: "https://www.nav.no/minside/"
    - name: DITT_SYKEFRAVAER_URL
      value: "https://ditt-sykefravaer.labs.nais.io/syk/sykefravaer"
    - name: MEROPPFOLGING_REGISTRERING_URL
      value: "https://demo.ekstern.dev.nav.no/syk/meroppfolging/reg/0"
    - name: ESYFOVARSEL_HOST
      value: "https://esyfovarsel.dev.intern.nav.no"
    - name: DECORATOR_ENV
      value: "prod"
    - name: AMPLITUDE_ENABLED
      value: "false"
  accessPolicy:
    outbound:
      rules:
        - application: nav-dekoratoren
          namespace: personbruker
      external:
        - host: www.nav.no
        - host: dekoratoren.ekstern.dev.nav.no
