name: Build & Deploy
on: push

jobs:
  next-app:
    uses: navikt/teamesyfo-github-actions-workflows/.github/workflows/next-app.yaml@main
    permissions:
      contents: read
      id-token: write
      packages: write
    secrets: inherit
    with:
      app: esyfo-info-frontend
      base-path: /syk/info
