name: Demo delete
on: delete

jobs:
  branch-delete:
    uses: navikt/teamesyfo-github-actions-workflows/.github/workflows/next-app-demo-delete.yaml@main
    secrets: inherit
    with:
      app: esyfo-info-frontend
      base-path: /syk/info
