name: Deploy to dev
on: workflow_dispatch
env:
  NPM_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
jobs:
  build:
    name: Bygg, test og push Docker image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          registry-url: 'https://npm.pkg.github.com'
      - name: Cache Cypress binary
        uses: actions/cache@v3
        with:
          path: ~/.cache/Cypress
          key: cypress-${{ runner.os }}-cypress-pr-${{ hashFiles('**/package.json') }}
          restore-keys: |
            cypress-${{ runner.os }}-cypress-
      - name: Install npm dependencies
        run: npm ci
      - name: Run prettier
        run: npm run prettier
      - name: Run lint
        run: npm run lint
      - name: Build application
        run: npm run build
      - name: Run cypress
        uses: cypress-io/github-action@v4
        with:
          install: false
          record: false
          start: npm run start-ingen-dekorator
          wait-on: http://localhost:8080/syk/info/api/isAlive
      - uses: actions/upload-artifact@v1
        if: ${{ always() }}
        with:
          name: cypress-screenshots
          path: cypress/screenshots
      - name: Build and push docker image
        uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: team-esyfo
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}

  deploy-dev:
    name: Deploy to dev-gcp
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: nais-dev.yaml
          VAR: image=${{ needs.build.outputs.image }}
